### ISSUE TITLE
example with functionalities

### ISSUE THREAD

**Issue by nicocheh** [vinid/prodb#3]
Hi! Awesome project, I read the paper and really want to try this idea! @vinid @patrickjohncyh 
I am trying to run the basic example provided in the readme and I get this error.

Do you have a notebook showing all basic functionalities or something like that?

Thank you!

Input In [24], in <cell line: 2>()
      1 #get_last_embeddings_for_sessions
----> 2 results = pb.run_next_item_predictions(next_element_prediction)

File ~/Desktop/Labs/notebooks/prodb/prodb/prodb.py:312, in ProdB.run_next_item_predictions(self, sessions, subword_prefix)
    310     joined = " ".join(splitted)
    311     gt.append(to_predict)
--> 312     predictions.append(self.predict_from_tokens(joined))
    313     pbar.update(1)
    314 pbar.close()

File ~/Desktop/Labs/notebooks/prodb/prodb/prodb.py:332, in ProdB.predict_from_tokens(self, string_ids)
    330 for i in range(len(top_indices)):
    331     p = top_indices[i]
--> 332     answers.append(self.convert_ids_to_tokens(p))
    334 return answers

File ~/Desktop/Labs/notebooks/prodb/prodb/prodb.py:230, in ProdB.convert_ids_to_tokens(self, id)
    229 def convert_ids_to_tokens(self, id):
--> 230     return self.id2token[id]

KeyError: 1497

**Comment by vinid** [comment]
Ah yes, the example is a bad example (my fault).

Here a colab that works: https://colab.research.google.com/drive/1YBF8b7zM2sRkQy1ZPiM3TXF35WaRTbTh?usp=sharing

**More Details**

You might get the error because you  have more vocabulary items than actual items in the training set:

Suppose you have

    VOCAB_SIZE = 20000

and only 5 distinct items in the training set ("item1 item2....").

when we get the top-10 best predictions for "item1 item2 [MASK]", the predictions will be a mix between your items and uninitialized vocab elements (20000 elements - 5 of your vocab). When the model access those uninitialized vocab positions, it breaks.

Note that the code comes from https://keras.io/examples/nlp/masked_language_modeling/ if you want to get the "original" version
